/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as MemberTaskDetailRouteImport } from './routes/member/task-detail'
import { Route as MemberMyTasksRouteImport } from './routes/member/my-tasks'
import { Route as MemberKanbanRouteImport } from './routes/member/kanban'
import { Route as ManagerProjectDetailRouteImport } from './routes/manager/project-detail'
import { Route as ManagerDashboardRouteImport } from './routes/manager/dashboard'
import { Route as ManagerCreateProjectRouteImport } from './routes/manager/create-project'
import { Route as ManagerAnalyticsRouteImport } from './routes/manager/analytics'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminSystemStatsRouteImport } from './routes/admin/system-stats'
import { Route as AdminAiSettingsRouteImport } from './routes/admin/ai-settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberTaskDetailRoute = MemberTaskDetailRouteImport.update({
  id: '/member/task-detail',
  path: '/member/task-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberMyTasksRoute = MemberMyTasksRouteImport.update({
  id: '/member/my-tasks',
  path: '/member/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberKanbanRoute = MemberKanbanRouteImport.update({
  id: '/member/kanban',
  path: '/member/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerProjectDetailRoute = ManagerProjectDetailRouteImport.update({
  id: '/manager/project-detail',
  path: '/manager/project-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerCreateProjectRoute = ManagerCreateProjectRouteImport.update({
  id: '/manager/create-project',
  path: '/manager/create-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
  id: '/manager/analytics',
  path: '/manager/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemStatsRoute = AdminSystemStatsRouteImport.update({
  id: '/admin/system-stats',
  path: '/admin/system-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiSettingsRoute = AdminAiSettingsRouteImport.update({
  id: '/admin/ai-settings',
  path: '/admin/ai-settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/system-stats': typeof AdminSystemStatsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/create-project': typeof ManagerCreateProjectRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/project-detail': typeof ManagerProjectDetailRoute
  '/member/kanban': typeof MemberKanbanRoute
  '/member/my-tasks': typeof MemberMyTasksRoute
  '/member/task-detail': typeof MemberTaskDetailRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/system-stats': typeof AdminSystemStatsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/create-project': typeof ManagerCreateProjectRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/project-detail': typeof ManagerProjectDetailRoute
  '/member/kanban': typeof MemberKanbanRoute
  '/member/my-tasks': typeof MemberMyTasksRoute
  '/member/task-detail': typeof MemberTaskDetailRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/system-stats': typeof AdminSystemStatsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/create-project': typeof ManagerCreateProjectRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/project-detail': typeof ManagerProjectDetailRoute
  '/member/kanban': typeof MemberKanbanRoute
  '/member/my-tasks': typeof MemberMyTasksRoute
  '/member/task-detail': typeof MemberTaskDetailRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/ai-settings'
    | '/admin/system-stats'
    | '/admin/teams'
    | '/admin/users'
    | '/manager/analytics'
    | '/manager/create-project'
    | '/manager/dashboard'
    | '/manager/project-detail'
    | '/member/kanban'
    | '/member/my-tasks'
    | '/member/task-detail'
    | '/user/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/ai-settings'
    | '/admin/system-stats'
    | '/admin/teams'
    | '/admin/users'
    | '/manager/analytics'
    | '/manager/create-project'
    | '/manager/dashboard'
    | '/manager/project-detail'
    | '/member/kanban'
    | '/member/my-tasks'
    | '/member/task-detail'
    | '/user/profile'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/ai-settings'
    | '/admin/system-stats'
    | '/admin/teams'
    | '/admin/users'
    | '/manager/analytics'
    | '/manager/create-project'
    | '/manager/dashboard'
    | '/manager/project-detail'
    | '/member/kanban'
    | '/member/my-tasks'
    | '/member/task-detail'
    | '/user/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAiSettingsRoute: typeof AdminAiSettingsRoute
  AdminSystemStatsRoute: typeof AdminSystemStatsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ManagerAnalyticsRoute: typeof ManagerAnalyticsRoute
  ManagerCreateProjectRoute: typeof ManagerCreateProjectRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerProjectDetailRoute: typeof ManagerProjectDetailRoute
  MemberKanbanRoute: typeof MemberKanbanRoute
  MemberMyTasksRoute: typeof MemberMyTasksRoute
  MemberTaskDetailRoute: typeof MemberTaskDetailRoute
  UserProfileRoute: typeof UserProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/task-detail': {
      id: '/member/task-detail'
      path: '/member/task-detail'
      fullPath: '/member/task-detail'
      preLoaderRoute: typeof MemberTaskDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/my-tasks': {
      id: '/member/my-tasks'
      path: '/member/my-tasks'
      fullPath: '/member/my-tasks'
      preLoaderRoute: typeof MemberMyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/kanban': {
      id: '/member/kanban'
      path: '/member/kanban'
      fullPath: '/member/kanban'
      preLoaderRoute: typeof MemberKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/project-detail': {
      id: '/manager/project-detail'
      path: '/manager/project-detail'
      fullPath: '/manager/project-detail'
      preLoaderRoute: typeof ManagerProjectDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/create-project': {
      id: '/manager/create-project'
      path: '/manager/create-project'
      fullPath: '/manager/create-project'
      preLoaderRoute: typeof ManagerCreateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/analytics': {
      id: '/manager/analytics'
      path: '/manager/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof ManagerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system-stats': {
      id: '/admin/system-stats'
      path: '/admin/system-stats'
      fullPath: '/admin/system-stats'
      preLoaderRoute: typeof AdminSystemStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-settings': {
      id: '/admin/ai-settings'
      path: '/admin/ai-settings'
      fullPath: '/admin/ai-settings'
      preLoaderRoute: typeof AdminAiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAiSettingsRoute: AdminAiSettingsRoute,
  AdminSystemStatsRoute: AdminSystemStatsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ManagerAnalyticsRoute: ManagerAnalyticsRoute,
  ManagerCreateProjectRoute: ManagerCreateProjectRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerProjectDetailRoute: ManagerProjectDetailRoute,
  MemberKanbanRoute: MemberKanbanRoute,
  MemberMyTasksRoute: MemberMyTasksRoute,
  MemberTaskDetailRoute: MemberTaskDetailRoute,
  UserProfileRoute: UserProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
