/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as MemberMyTasksRouteImport } from './routes/member/my-tasks'
import { Route as MemberKanbanRouteImport } from './routes/member/kanban'
import { Route as ManagerKanbanRouteImport } from './routes/manager/kanban'
import { Route as ManagerDashboardRouteImport } from './routes/manager/dashboard'
import { Route as ManagerCreateProjectRouteImport } from './routes/manager/create-project'
import { Route as ManagerAnalyticsRouteImport } from './routes/manager/analytics'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminSystemStatsRouteImport } from './routes/admin/system-stats'
import { Route as AdminAiSettingsRouteImport } from './routes/admin/ai-settings'
import { Route as MemberTasksTaskIdRouteImport } from './routes/member/tasks.$taskId'
import { Route as ManagerTasksTaskIdRouteImport } from './routes/manager/tasks.$taskId'
import { Route as ManagerProjectsProjectIdRouteImport } from './routes/manager/projects.$projectId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberMyTasksRoute = MemberMyTasksRouteImport.update({
  id: '/member/my-tasks',
  path: '/member/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberKanbanRoute = MemberKanbanRouteImport.update({
  id: '/member/kanban',
  path: '/member/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerKanbanRoute = ManagerKanbanRouteImport.update({
  id: '/manager/kanban',
  path: '/manager/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerCreateProjectRoute = ManagerCreateProjectRouteImport.update({
  id: '/manager/create-project',
  path: '/manager/create-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
  id: '/manager/analytics',
  path: '/manager/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemStatsRoute = AdminSystemStatsRouteImport.update({
  id: '/admin/system-stats',
  path: '/admin/system-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiSettingsRoute = AdminAiSettingsRouteImport.update({
  id: '/admin/ai-settings',
  path: '/admin/ai-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberTasksTaskIdRoute = MemberTasksTaskIdRouteImport.update({
  id: '/member/tasks/$taskId',
  path: '/member/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTasksTaskIdRoute = ManagerTasksTaskIdRouteImport.update({
  id: '/manager/tasks/$taskId',
  path: '/manager/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerProjectsProjectIdRoute =
  ManagerProjectsProjectIdRouteImport.update({
    id: '/manager/projects/$projectId',
    path: '/manager/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/system-stats': typeof AdminSystemStatsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/create-project': typeof ManagerCreateProjectRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/kanban': typeof ManagerKanbanRoute
  '/member/kanban': typeof MemberKanbanRoute
  '/member/my-tasks': typeof MemberMyTasksRoute
  '/user/profile': typeof UserProfileRoute
  '/manager/projects/$projectId': typeof ManagerProjectsProjectIdRoute
  '/manager/tasks/$taskId': typeof ManagerTasksTaskIdRoute
  '/member/tasks/$taskId': typeof MemberTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/system-stats': typeof AdminSystemStatsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/create-project': typeof ManagerCreateProjectRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/kanban': typeof ManagerKanbanRoute
  '/member/kanban': typeof MemberKanbanRoute
  '/member/my-tasks': typeof MemberMyTasksRoute
  '/user/profile': typeof UserProfileRoute
  '/manager/projects/$projectId': typeof ManagerProjectsProjectIdRoute
  '/manager/tasks/$taskId': typeof ManagerTasksTaskIdRoute
  '/member/tasks/$taskId': typeof MemberTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/system-stats': typeof AdminSystemStatsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/create-project': typeof ManagerCreateProjectRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/kanban': typeof ManagerKanbanRoute
  '/member/kanban': typeof MemberKanbanRoute
  '/member/my-tasks': typeof MemberMyTasksRoute
  '/user/profile': typeof UserProfileRoute
  '/manager/projects/$projectId': typeof ManagerProjectsProjectIdRoute
  '/manager/tasks/$taskId': typeof ManagerTasksTaskIdRoute
  '/member/tasks/$taskId': typeof MemberTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/admin/ai-settings'
    | '/admin/system-stats'
    | '/admin/teams'
    | '/admin/users'
    | '/manager/analytics'
    | '/manager/create-project'
    | '/manager/dashboard'
    | '/manager/kanban'
    | '/member/kanban'
    | '/member/my-tasks'
    | '/user/profile'
    | '/manager/projects/$projectId'
    | '/manager/tasks/$taskId'
    | '/member/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/admin/ai-settings'
    | '/admin/system-stats'
    | '/admin/teams'
    | '/admin/users'
    | '/manager/analytics'
    | '/manager/create-project'
    | '/manager/dashboard'
    | '/manager/kanban'
    | '/member/kanban'
    | '/member/my-tasks'
    | '/user/profile'
    | '/manager/projects/$projectId'
    | '/manager/tasks/$taskId'
    | '/member/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/admin/ai-settings'
    | '/admin/system-stats'
    | '/admin/teams'
    | '/admin/users'
    | '/manager/analytics'
    | '/manager/create-project'
    | '/manager/dashboard'
    | '/manager/kanban'
    | '/member/kanban'
    | '/member/my-tasks'
    | '/user/profile'
    | '/manager/projects/$projectId'
    | '/manager/tasks/$taskId'
    | '/member/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyRoute: typeof VerifyRoute
  AdminAiSettingsRoute: typeof AdminAiSettingsRoute
  AdminSystemStatsRoute: typeof AdminSystemStatsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ManagerAnalyticsRoute: typeof ManagerAnalyticsRoute
  ManagerCreateProjectRoute: typeof ManagerCreateProjectRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerKanbanRoute: typeof ManagerKanbanRoute
  MemberKanbanRoute: typeof MemberKanbanRoute
  MemberMyTasksRoute: typeof MemberMyTasksRoute
  UserProfileRoute: typeof UserProfileRoute
  ManagerProjectsProjectIdRoute: typeof ManagerProjectsProjectIdRoute
  ManagerTasksTaskIdRoute: typeof ManagerTasksTaskIdRoute
  MemberTasksTaskIdRoute: typeof MemberTasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/my-tasks': {
      id: '/member/my-tasks'
      path: '/member/my-tasks'
      fullPath: '/member/my-tasks'
      preLoaderRoute: typeof MemberMyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/kanban': {
      id: '/member/kanban'
      path: '/member/kanban'
      fullPath: '/member/kanban'
      preLoaderRoute: typeof MemberKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/kanban': {
      id: '/manager/kanban'
      path: '/manager/kanban'
      fullPath: '/manager/kanban'
      preLoaderRoute: typeof ManagerKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/create-project': {
      id: '/manager/create-project'
      path: '/manager/create-project'
      fullPath: '/manager/create-project'
      preLoaderRoute: typeof ManagerCreateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/analytics': {
      id: '/manager/analytics'
      path: '/manager/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof ManagerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system-stats': {
      id: '/admin/system-stats'
      path: '/admin/system-stats'
      fullPath: '/admin/system-stats'
      preLoaderRoute: typeof AdminSystemStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-settings': {
      id: '/admin/ai-settings'
      path: '/admin/ai-settings'
      fullPath: '/admin/ai-settings'
      preLoaderRoute: typeof AdminAiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/tasks/$taskId': {
      id: '/member/tasks/$taskId'
      path: '/member/tasks/$taskId'
      fullPath: '/member/tasks/$taskId'
      preLoaderRoute: typeof MemberTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/tasks/$taskId': {
      id: '/manager/tasks/$taskId'
      path: '/manager/tasks/$taskId'
      fullPath: '/manager/tasks/$taskId'
      preLoaderRoute: typeof ManagerTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/projects/$projectId': {
      id: '/manager/projects/$projectId'
      path: '/manager/projects/$projectId'
      fullPath: '/manager/projects/$projectId'
      preLoaderRoute: typeof ManagerProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyRoute: VerifyRoute,
  AdminAiSettingsRoute: AdminAiSettingsRoute,
  AdminSystemStatsRoute: AdminSystemStatsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ManagerAnalyticsRoute: ManagerAnalyticsRoute,
  ManagerCreateProjectRoute: ManagerCreateProjectRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerKanbanRoute: ManagerKanbanRoute,
  MemberKanbanRoute: MemberKanbanRoute,
  MemberMyTasksRoute: MemberMyTasksRoute,
  UserProfileRoute: UserProfileRoute,
  ManagerProjectsProjectIdRoute: ManagerProjectsProjectIdRoute,
  ManagerTasksTaskIdRoute: ManagerTasksTaskIdRoute,
  MemberTasksTaskIdRoute: MemberTasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
